### ISSUE TITLE
API Manager can't connect to Cassandra

### ISSUE THREAD

**Issue by dokuboyejo** [Axway/Cloud-Automation#23]
it seems the api manager is failing to successfully connect to the cassandra internal cluster

`
INFO    04/Feb/2022:07:52:07.617 [0001:000000000000000000000000]     cert store configured
INFO    04/Feb/2022:07:52:07.621 [0001:000000000000000000000000]     Loading KPS configuration.
ERROR   04/Feb/2022:07:52:14.322 [0001:000000000000000000000000]         Authentication error on host cassandra/10.96.244.52:9042: Password must not be null
ERROR   04/Feb/2022:07:52:14.324 [0001:000000000000000000000000]         Error initializing Cassandra schemas: 
java.lang.RuntimeException: The Cassandra connection has not been set up
        at com.axway.apigw.cassandra.impl.datastax.ClusterConnectionPoolService.createOrUpdateCluster(ClusterConnectionPoolService.java:99)
        at com.vordel.kps.storeImpl.cassandra.CassandraStore.getOrCreateCurrentCassandraClient(CassandraStore.java:550)
        at com.vordel.kps.storeImpl.cassandra.CassandraStore.createCassandraClient(CassandraStore.java:280)
        at com.vordel.kps.storeImpl.cassandra.CassandraSchema.initKeyspace(CassandraSchema.java:58)
        at com.vordel.kps.storeImpl.cassandra.CassandraSchema.initSchemas(CassandraSchema.java:45)
        at com.vordel.kps.impl.KPS.initialiseCassandraSchema(KPS.java:245)
        at com.vordel.kps.impl.KPS.load(KPS.java:219)
        at com.vordel.kps.impl.KPS.configure(KPS.java:179)
        at com.vordel.precipitate.SolutionPack$ConfigModule.configure(SolutionPack.java:319)
        at com.vordel.precipitate.SolutionPack.loadModules(SolutionPack.java:439)
        at com.vordel.dwe.Service.refresh(Service.java:578)
        at com.vordel.dwe.Service.<init>(Service.java:479)

INFO    04/Feb/2022:07:52:14.324 [0001:000000000000000000000000]     Cassandra keyspace: null
INFO    04/Feb/2022:07:52:14.324 [0001:000000000000000000000000]     Cassandra hosts: null
INFO    04/Feb/2022:07:52:14.324 [0001:000000000000000000000000]     Authentication not configured for Cassandra connection
INFO    04/Feb/2022:07:52:14.324 [0001:000000000000000000000000]     Checking for passphrase changes...
ERROR   04/Feb/2022:07:52:14.416 [0001:000000000000000000000000]     Schema check failed for store: [API Portal_ApiAppPolicyBindings, API Portal_ApiOrgPolicyBindings, API Portal_ApiPolicyParameters, API Portal_PortalAPI, API Portal_PortalAPIMethod, API Portal_PortalActionQueue, API Portal_PortalApiAccessStore, API Portal_PortalApiQuotaConstraintStore, API Portal_PortalApiQuotaDetailsStore, API Portal_PortalApiQuotaStore, API Portal_PortalApplicationPermissionStore, API Portal_PortalConfigStore, API Portal_PortalExports, API Portal_PortalIdentityStore, API Portal_PortalOrganizationStore, API Portal_PortalOrganizationStoreLDAP, API Portal_PortalRegistrationToken, API Portal_PortalRemoteHost, API Portal_PortalTimestamp, API Portal_PortalUserStore, API Portal_PortalUserStoreLDAP, API Portal_PortalVirtualizedAPI, API Portal_PortalVirtualizedAPIMethod, API Server_PortalApiKeyStore, API Server_PortalApplicationStore, API Server_PortalExternalClientStore, API Server_PortalOAuthResourcesStore, API Server_PortalOAuthStore, OAuth_AccessTokens, OAuth_AuthZCodes, OAuth_Authorizations, OAuth_ClientAccessTokens, OAuth_ClientRefreshTokens, OAuth_RefreshTokens]: 
java.lang.IllegalArgumentException: The Cassandra connection has not been set up
        at org.springframework.util.Assert.isTrue(Assert.java:92)
        at com.axway.apigw.cassandra.impl.datastax.ClusterConnectionPoolService.getSession(ClusterConnectionPoolService.java:173)
        at com.axway.apigw.cassandra.impl.datastax.kps.BasicDmlOperationsImpl.getById(BasicDmlOperationsImpl.java:60)
        at com.vordel.kps.storeImpl.cassandra.CassandraStore.primaryKeyQuery(CassandraStore.java:428)
        at com.vordel.kps.storeImpl.cassandra.CassandraStore.get(CassandraStore.java:383)
        at com.vordel.kps.storeImpl.cassandra.CassandraTransaction.getInternal(CassandraTransaction.java:52)
        at com.vordel.kps.storeImpl.AbstractTransaction.get(AbstractTransaction.java:118)
        at com.vordel.kps.storeImpl.AbstractTransaction.get(AbstractTransaction.java:146)
        at com.vordel.kps.admin.Schema.initSchema(Schema.java:250)
        at com.vordel.kps.admin.Schema.<init>(Schema.java:117)
        at com.vordel.kps.admin.Schema.checkForChanges(Schema.java:67)
        at com.vordel.kps.impl.KPS.load(KPS.java:220)
        at com.vordel.kps.impl.KPS.configure(KPS.java:179)
        at com.vordel.precipitate.SolutionPack$ConfigModule.configure(SolutionPack.java:319)
        at com.vordel.precipitate.SolutionPack.loadModules(SolutionPack.java:439)
        at com.vordel.dwe.Service.refresh(Service.java:578)
        at com.vordel.dwe.Service.<init>(Service.java:479)

INFO    04/Feb/2022:07:52:14.416 [0001:000000000000000000000000]     No passphrase changes detected.
ERROR   04/Feb/2022:07:52:14.819 [0001:000000000000000000000000]     Cannot initialize quota stores: 
java.lang.IllegalArgumentException: The Cassandra connection has not been set up
        at org.springframework.util.Assert.isTrue(Assert.java:92)
        at com.axway.apigw.cassandra.impl.datastax.ClusterConnectionPoolService.getSession(ClusterConnectionPoolService.java:173)
        at com.axway.apigw.cassandra.impl.datastax.kps.BasicDmlOperationsImpl.getById(BasicDmlOperationsImpl.java:60)
        at com.vordel.kps.storeImpl.cassandra.CassandraStore.primaryKeyQuery(CassandraStore.java:428)
        at com.vordel.kps.storeImpl.cassandra.CassandraStore.get(CassandraStore.java:383)
        at com.vordel.kps.storeImpl.cassandra.CassandraTransaction.getInternal(CassandraTransaction.java:52)
        at com.vordel.kps.storeImpl.AbstractTransaction.get(AbstractTransaction.java:118)
        at com.vordel.kps.TableInternal.readRecord(TableInternal.java:53)
        at com.vordel.kps.TableInternal.readRecord(TableInternal.java:29)
        at com.vordel.kps.storeImpl.AbstractStore.getCached(AbstractStore.java:119)
        at com.vordel.apiportal.api.portal.controller.ApiQuotaController.isQuotaExist(ApiQuotaController.java:653)
        at com.vordel.apiportal.api.portal.controller.ApiQuotaController.createMissingSystemQuota(ApiQuotaController.java:82)
        at com.vordel.apiportal.api.portal.controller.ApiQuotaController.initializeQuotaStores(ApiQuotaController.java:73)
        at com.vordel.apiportal.config.PortalConfiguration.initializeQuotaSystem(PortalConfiguration.java:380)
        at com.vordel.apiportal.config.PortalConfiguration.configure(PortalConfiguration.java:225)
        at com.vordel.precipitate.SolutionPack$ConfigModule.configure(SolutionPack.java:319)
        at com.vordel.precipitate.SolutionPack.loadModules(SolutionPack.java:439)
        at com.vordel.dwe.Service.refresh(Service.java:578)
        at com.vordel.dwe.Service.<init>(Service.java:479)

ERROR   04/Feb/2022:07:52:14.936 [0001:000000000000000000000000]     Failed to configure API Manager

com.vordel.es.EntityStoreException: Fatal exception throwed: '/[PortalConfiguration]name=Portal Config' reason: 'The Cassandra connection has not been set up'
        at com.vordel.precipitate.SolutionPack.throwit(SolutionPack.java:479)
        at com.vordel.precipitate.SolutionPack.loadModules(SolutionPack.java:441)
        at com.vordel.dwe.Service.refresh(Service.java:578)
        at com.vordel.dwe.Service.<init>(Service.java:479)
Caused by: com.vordel.config.LoadableModule$FatalException: The Cassandra connection has not been set up
        at com.vordel.apiportal.config.PortalConfiguration.configure(PortalConfiguration.java:237)
        at com.vordel.precipitate.SolutionPack$ConfigModule.configure(SolutionPack.java:319)
        at com.vordel.precipitate.SolutionPack.loadModules(SolutionPack.java:439)
        ... 2 more

INFO    04/Feb/2022:07:52:15.021 [001b:000000000000000000000000] Management Service - Pipe Server Stopping
`

**Comment by cwiechmann** [comment]
This is the cause of the problem:
> Password must not be null

Unfortunately, the API-Manager configuration must be a bit prepared in order to connect to Cassandra. By default the Cassandra-AuthN is not set, which is not allowed anymore with C* 3.x.x. 

With the following settings, the Environment-Variables `CASS_USERNAME` and `CASS_PASS`, which are populated by the Helm-Chart into the Container, will be picked up the API-Gateway to connect to Cassandra:
![image](https://user-images.githubusercontent.com/16292002/152501806-2f055c0f-85ef-411f-bc6b-5593212fef8e.png)

See the default values.yaml comment:
https://github.com/Axway/Cloud-Automation/blob/87f3a040053f548dba8cafa23aa36b06e0b881d0/APIM/Helmchart/values.yaml#L915-L921

**Comment by dokuboyejo** [comment]
@cwiechmann 
Thanks, so I can see the env vars being pulled using the default values which is correct for the test exercise, however it still complains of password being null

![Screenshot from 2022-02-04 12-39-59](https://user-images.githubusercontent.com/969476/152515860-f9c5e6e5-c959-4f6c-8183-8d3a8e26d285.png)

**Comment by cwiechmann** [comment]
Have you re-build your API-Gatway image including the setting mentioned above in Policy-Studio?

**Comment by dokuboyejo** [comment]
@cwiechmann  I really do not get that properly. Do we need to re-build the api-gateway image with both CASS_USERNAME and CASS_PASS environment variable. I thought since the two environment variables are available at runtimes, the container is able to pick them as displayed in the pod env vars.
I built the test images directly from shell terminal. The part I really do not get properly is what you mentioned about building the image with policy studio.
Would appreciate further guidance

**Comment by cwiechmann** [comment]
The environment variables are injected into container, but the application (the API-Gateway) is not using them, as the current configuration is not referencing them. 

Therefore, you need to use Policy-Studio to configure the reference to the environment variables and build the image (in your shell), but provide the FED (using the parameter `--fed`) you modified with Policy-Studio. Don't use any factory fed for this.

**Comment by dokuboyejo** [comment]
@cwiechmann  usage of the custom fed file worked ... many thanks

**Comment by cwiechmann** [comment]
Thanks for the feedback.
